name: Publish Homoglyphs

env:
  name: homoglyphs_fork

on:
  release:
    types:
      - released

jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install CA certs
        run: sudo apt-get install ca-certificates -y
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Publish to PyPI
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API }}
        run: |
          # specify the version to publish
          uv build
          uv publish --token
