name: Publish Homoglyphs

env:
  name: homoglyphs_fork

on:
  release:
    types:
      - released

jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install CA certs
        run: sudo apt-get install ca-certificates -y
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: eifinger/setup-rye@v4
      - name: Publish to PyPI
        run: |
          rye version ${{ github.event.release.tag_name }}
          rye build
          rye publish --yes --token ${{ secrets.PYPI_API }}
